
server:
  port: 9092

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/saas-booking
    username: pos-booking
    password: pos-booking
  jpa:
    hibernate:
      ddl-auto: update   # or create / create-drop
    show-sql: true
#  // ── application.yml ──────────────────────────────────────────────────────────

jwt:
  secret: Zmx5bmVzdC1zZWNyZXQta2V5LW11c3QtYmUtYXQtbGVhc3QtMjU2LWJpdHMtbG9uZw==
  expiration: 86400000