#version: "3.9"
#
#services:
#  mysql:
#    image: mysql:8.0
#    container_name: saas-pos-mysql-db
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: saas-pos
#      MYSQL_USER: pos-user
#      MYSQL_PASSWORD: pos-password
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql
#
#volumes:
#  mysql_data:



version: "3.9"  # Docker Compose version

services:

  # -------------------------------
  # MYSQL DATABASE SERVICE
  # -------------------------------
  mysql:
    image: mysql:8.0  # Official MySQL image
    container_name: booking-mysql-db
    restart: always  # Auto restart if container crashes

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: saas-booking
      MYSQL_USER: pos-booking
      MYSQL_PASSWORD: pos-booking

    ports:
      - "3306:3306"  # Host:Container

    volumes:
      - mysql_data:/var/lib/mysql  # Persist DB data

    # Health check to ensure DB is ready
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5


volumes:
  mysql_data:  # Correct volume name